log_level: TRACE
iam:
  url: 'https://iam.netsoc.ie/v1'
  token: A.B.C
  allow_insecure: false
lxd:
  url: https://localhost
  tls:
    ca:
    server_cert:
    client_cert:
    client_key:
    trust_password: hunter2
    allow_insecure: false
  network: lxdbr0
webspaces:
  profile: webspace
  instance_prefix: 'ws-'
  domain: .ng.localhost
  config_defaults:
    startup_delay: 3
    http_port: 80
    https_port: 443
  max_startup_delay: 60
  run_limit: 32
  ports:
    start: 49152
    end: 65535
    max: 64
