version: '3'
services:
  #redis:
  #  image: redis:alpine
  #  command:
  #    - --save
  #    - ''
  #    - --appendonly
  #    - 'no'
  #  ports:
  #    - 127.0.0.1:6379:6379
  #  network_mode: host

  # For Redis provider
  #traefik:
  #  image: ghcr.io/netsoc/webspaced/traefik:dev
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.traefik
  #  image: ghcr.io/netsoc/webspaced/traefik
  #  command:
  #    - --providers.file.filename=/static.yaml
  #    - --entryPoints.http.address=:80
  #    - --entryPoints.https.address=:443
  #    - --api.dashboard=true
  #    - --accesslog=true
  #  environment:
  #    - REDIS_HOST=localhost
  #  volumes:
  #    - ./traefik-static.yaml:/static.yaml:ro
  #  network_mode: host

  app:
    image: ghcr.io/netsoc/webspaced:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - WSD_LOG_LEVEL=debug
      - WSD_IAM_URL=http://localhost:8080/v1
      - WSD_IAM_ALLOW_INSECURE=true
      - WSD_LXD_TLS_ALLOW_INSECURE=true
      - WSD_LXD_TLS_CLIENT_CERT_FILE=/run/certs/client.crt
      - WSD_LXD_TLS_CLIENT_KEY_FILE=/run/certs/client.key
      - WSD_HTTP_LISTEN_ADDRESS=:8081
      - WSD_TRAEFIK_WEBSPACED_URL=http://172.19.0.1:8081
      - WSD_TRAEFIK_PROVIDER=kubernetes
      - WSD_TRAEFIK_KUBERNETES_NAMESPACE=webspace-ng
      - WSD_TRAEFIK_HTTPS_ENTRYPOINT=websecure
      - KUBECONFIG=/run/config/kubeconfig.yaml
    volumes:
      - .:/usr/local/lib/webspaced
      - ./certs:/run/certs:ro
      - ./kubeconfig-proxy.yaml:/run/config/kubeconfig.yaml:ro
    network_mode: host
