name: Docker Images

on:
  push:
    branches:
      - develop
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest

    env:
      DOCKER_COMPOSE_FILE: webspaced/docker-compose.release.yaml

    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build images
        run: docker-compose -f "$DOCKER_COMPOSE_FILE" build

      - name: Push images
        run: docker-compose -f "$DOCKER_COMPOSE_FILE" push
